# Generated by Django 4.1.7 on 2023-05-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('detail1_name', models.CharField(max_length=100)),
                ('detail1_description', models.TextField()),
                ('detail2_name', models.CharField(max_length=100)),
                ('detail2_description', models.TextField()),
                ('detail3_name', models.CharField(max_length=100)),
                ('detail3_description', models.TextField()),
            ],
        ),
    ]
