# Generated by Django 4.1.7 on 2023-06-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sortIT_main', '0005_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='locationId',
        ),
        migrations.RemoveField(
            model_name='location',
            name='state',
        ),
    ]
