# Generated by Django 4.1.7 on 2023-06-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortIT_main', '0008_ecoshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipsTricks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('detail1_description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'TipsTricks',
            },
        ),
    ]
